plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
    id "me.modmuss50.mod-publish-plugin" version "2.0.1"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url 'https://maven.nucleoid.xyz' }
    maven { url 'https://jitpack.io' }
    maven { url 'https://masa.dy.fi/maven' }
}

loom {
    accessWidenerPath = file("src/main/resources/fabrictailor.accesswidener")

}


def ENV = System.getenv()

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // Config2Brigadier
    implementation(include("com.github.samolego:Config2Brigadier:${project.c2b_lib_version}"))

    // LuckPerms
    implementation(include("me.lucko:fabric-permissions-api:${project.permissions_api_version}"))

    // Carpet
//    compileOnly("carpet:fabric-carpet:${project.carpet_core_version}")
}   

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

tasks.test {
    failOnNoDiscoveredTests = false
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}"}
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}

// Publishing to CurseForge / Modrinth, modeled after Fabric API's build:
publishMods {
    file = jar.archiveFile
    changelog = ENV.CHANGELOG ?: "A changelog can be found at https://github.com/samolego/FabricTailor/releases/tag/${version}"
    type = STABLE
    displayName = "[${project.minecraft_version}] FabricTailor ${version}"
    modLoaders.addAll("fabric", "quilt")
    dryRun = providers.environmentVariable("CURSEFORGE_API_KEY").getOrNull() == null

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")
        projectId = "390114"
        minecraftVersions.add(project.minecraft_version)
        client = true
        server = true
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "g8w1NapE"
        minecraftVersions.add(project.minecraft_version)
    }
}
