name: Build

on:
  release:
    types:
      - published
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: JDK Setup
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Gradle Setup
        uses: gradle/actions/setup-gradle@v5
        with:
          validate-wrappers: true

      - name: Enable gradlew execution
        run: chmod +x ./gradlew

      - name: Gradle Build
        run: ./gradlew build

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: 'build/libs/*.jar, !build/libs/*-sources.jar'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
